# Generated by Django 3.0.9 on 2020-11-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Klass')),
            ],
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('presence', models.BooleanField()),
                ('on_leave', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Klass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subject')),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Teacher')),
            ],
        ),
    ]
